POST http://localhost:3000/customer
Content-Type: application/json

{
  "customer": {
    "cnpj": "92.549.468/0001-58",
    "corporateName": "Mercado Bom Preço LTDA",
    "contactName": "Mercado Bom Preço",
    "phone": "(23)429192302"
  },
  "addresses": [
    {
      "publicPlace": "Praça da bandeira",
      "addressNumber": 123,
      "district": "Bairro boa Vista",
      "city": "Ghapecó",
      "state": "SC",
      "cep": "89.801-023"
    },
    {
      "publicPlace": "Praça da bandeira",
      "addressNumber": 18,
      "district": "Bairro Esperança",
      "city": "Balneário",
      "state": "SC",
      "cep": "88.330-015"
    }
  ]
}

###
GET http://localhost:3000/customer?cnpj=92.549.468/0001-58
Content-Type: application/json

###
PUT http://localhost:3000/customer
Content-Type: application/json

{
  "customer": {
    "cnpj": "92.549.468/0001-58",
    "corporateName": "Mercado Preço Bom LTDA",
    "contactName": "Mercado Preço Bom",
    "phone": "(24)291923028"
  }
}

###
DELETE http://localhost:3000/customer?cnpj=92.549.468/0001-58

###
GET http://localhost:3000/address?cnpj=92.549.468/0001-58
Content-Type: application/json

###
PUT http://localhost:3000/address
Content-Type: application/json

{
  "address": {
    "publicPlace": "Prainha",
    "addressNumber": 18,
    "district": "Bairro",
    "city": "Balneário",
    "state": "SC",
    "cep": "88.330-015",
    "customerCnpj": "92.549.468/0001-58"
  }
}

###
POST http://localhost:3000/address
Content-Type: application/json

{
  "address":{
    "publicPlace": "Praça da Paz",
    "addressNumber": 126,
    "district": "Vila das Flores",
    "city": "Estação",
    "state": "SP",
    "cep": "13.484-019",
    "customerCnpj": "92.549.468/0001-58"
  }
}

###
DELETE http://localhost:3000/address?cnpj=92.549.468/0001-58&cep=13.484-019&addressNumber=126