POST http://localhost:3000/customer
Content-Type: application/json

{
  "customer": {
    "cnpj": "92.549.468/0001-58",
    "corporateName": "any",
    "contactName": "any",
    "phone": "23429192302"
  },
  "addresses": [
    {
      "publicPlace": "Praça da bandeira",
      "addressNumber": 123,
      "complement": "",
      "district": "any",
      "city": "any",
      "state": "any",
      "cep": "99.735-000"
    },
    {
      "publicPlace": "Praça da bandeira",
      "addressNumber": 125,
      "complement": "",
      "district": "any",
      "city": "any",
      "state": "any",
      "cep": "99.735-000"
    }
  ]
}

###
GET http://localhost:3000/
Content-Type: application/json

###
DELETE http://localhost:3000/134123412343234
